### ISSUE TITLE
The bundled version of Amplitude's Android SDK is out of date

### ISSUE THREAD

**Issue by djih** [segment-integrations/analytics-android-integration-amplitude#46]
Wanted to get some more visibility on this issue (originally reported in: https://github.com/segment-integrations/analytics-android-integration-amplitude/pull/45)

@f2prateek I just noticed an issue. So this entire time I've been bumping the Amplitude Android SDK version in the build.gradle file, but it doesn't seem like it's actually updating the version?

I have a test Android app where I installed Segment and bundled Amplitude's SDK. I'm noticing that it's installing v2.2.0 of our SDK, which was released like over 2 years ago, instead of the latest version.

Is there something else I need to update to fix this? This is rather urgent as this means our Segment bundled integration has not been receiving updates for the last 2 years.

**Comment by djih** [comment]
False alarm, looks like everything is good

**Comment by f2prateek** [comment]
The latest release for this integration is version 2.0.0. This version is using the version in the `build.gradle` defined in https://github.com/segment-integrations/analytics-android-integration-amplitude/blob/2.0.0/build.gradle#L44. This version is using 2.15.0 of Amplitude. This is also what I see in Maven as the transitive dependency. (http://search.maven.org/#artifactdetails%7Ccom.segment.analytics.android.integrations%7Camplitude%7C2.0.0%7Cjar)

>I have a test Android app where I installed Segment and bundled Amplitude's SDK. I'm noticing that it's installing v2.2.0 of our SDK, which was released like over 2 years ago, instead of the latest version.

Which version of the Segment Amplitude integration did you use? Was it 2.0.0 (which is the latest)? Is it possible you were using an older version of the integration that pulled in an older version of Amplitude?

Also for reference, every time we update the version in the `build.gradle`; we'd have to make a release to this integration as well so that it's automatically picked up by customers.

**Comment by djih** [comment]
I realized I too was using a older version (1.0.0) of the integration, so it was pulling in v2.2.0 of our SDK. I changed it to just use `+` and it pulled the latest for everything. Silly mistake on my part
